name: CI Entry

on:
  workflow_dispatch:
    inputs:
      distribution-channel:
        description: Distribution channel for release. It can be `beta`, `alpha`, or any string.
        type: string
        required: true
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.idea/**'
      - '.vscode/**'

permissions:
  contents: write

jobs:
  run-ci-for-template:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: ${{ inputs.distribution-channel }}
      renderer-template: "react-swc-ts"
