name: Compile and test

on:
  workflow_call:
    inputs:
      renderer-template:
        description: Define what vite template should be used to create renderer in case if renderer package doesn't exist
        required: false
        type: string
        default: ''
      app-version:
        required: true
        type: string
      distribution-channel:
        required: true
        type: string

defaults:
  run:
    shell: 'bash'

permissions:
  contents: write
  id-token: write
  attestations: write

env:
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_audit: false
  npm_config_fund: false
  DEBUG: "electron:*,pw:api" # Enable Electron and Playwright debug logs

jobs:
  typeckeck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-template-with-renderer
        name: Setup boilerplate
        with:
          renderer-template: ${{inputs.renderer-template}}
      - run: npm run typecheck --if-present

  compile:
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-template-with-renderer
        name: Setup boilerplate
        with:
          renderer-template: ${{inputs.renderer-template}}

      - run: npm version "${{inputs.app-version}}" --no-git-tag-version

      # Install dependencies for Electron
      - name: Install dependencies for Electron
        if: matrix.os == 'ubuntu-latest' # Only needed for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxcomposite1 \
            libxrandr2 \
            libasound2t64 \
            libpangocairo-1.0-0 \
            libpango-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libgtk-3-0

      # Debug: Print environment variables
      - name: Print environment variables
        run: env

      # Debug: Check for missing dependencies
      - name: Check missing libraries
        run: |
          ldd node_modules/electron/dist/electron | grep "not found" || echo "All dependencies found"

      # Compile the app
      - run: npm run compile -- -p never
        env:
          VITE_DISTRIBUTION_CHANNEL: ${{inputs.distribution-channel}}

      # Debug: Capture Electron logs
      - name: Run tests with Electron debug logs
        env:
          DEBUG: "electron:*,pw:api"
        run: npm run test --if-present

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: "dist/root*, dist/latest*.yml"

      - name: Upload compiled app
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{inputs.distribution-channel}}
          path: dist
